return {
    { "n", "<Leader>fh", "<cmd>Telescope oldfiles<CR>", { desc = "Open file history" } },
    { "n", "<Leader>ff", "<cmd>Telescope find_files<CR>", { desc = "Find files in cwd" } },
    { "n", "<Leader>tc", "<cmd>Telescope colorscheme<CR>", { desc = "Change colorscheme" } },
    { "n", "<Leader>fw", "<cmd>Telescope live_grep<CR>", { desc = "Find word in workspace" } },
    { "n", "<Leader>cn", "<cmd>enew<CR>", { desc = "Create new file" } },
    { "n", "<Leader>fp", "<cmd>Telescope projects<cr>", { desc = "Project history" } },
    { "n", "<Leader>ss", "e " .. vim.fn.stdpath("config") .. "/" .. "init.lua", { desc = "Open Settings" } },
    { { "n", "i" }, "<C-k>p", "<cmd>Telescope find_files<cr>", { desc = "find file" } },
    { { "n", "i" }, "<C-k>s", "<cmd>Telescope lsp_document_symbols<cr>", { desc = "show document symboles" } },
    {
        { "n", "i" },
        "<C-k><S-s>",
        "<cmd>Telescope lsp_workspace_symbols<cr>",
        { desc = "show workspace symboles" },
    },
    { { "n", "i" }, "<C-k>f", "<cmd>Telescope live_grep<cr>", { desc = "find word in workspace" } },
    { { "n", "i" }, "<C-k>r", "<cmd>Telescope registers<cr>", { desc = "look up registers" } },
    { "n", "z=", "<cmd>Telescope spell_suggest<cr>", { desc = "spell suggest" } },
    { { "n", "i" }, "<C-k><C-o>", "<cmd>Telescope file_browser<cr>", { desc = "open file browser" } },
    { { "n", "i" }, "<C-b>", "<cmd>Telescope buffers<cr>", { desc = "open buffers" } },
}
